/**
 * Pure generator for supabase/migrations/003_seed_foods.sql (system food catalog seed).
 * Node-safe: run by scripts/generate-seed-sql.ts, and re-run in tests to prove the committed file is current.
 */
import { NUTRIENT_KEYS } from '../types/nutrition.ts'
import type { FoodRow } from './foodRow.ts'
import {
  sqlBoolean,
  sqlInteger,
  sqlJsonb,
  sqlNullableString,
  sqlString,
  sqlTextArray,
  sqlTimestamptz,
  sqlUuid,
} from './sqlLiterals.ts'

/** public.food_items columns in 001_initial_schema.sql order. */
export const FOOD_ITEM_COLUMNS = [
  'id',
  'source',
  'external_id',
  'name',
  'brand',
  'barcode',
  'category',
  'nutrients_per_100g',
  'servings',
  'allergens',
  'is_vegetarian',
  'is_vegan',
  'tags',
  'meal_types',
  'prep_minutes',
  'requires_cooking',
  'cost_tier',
  'attribution',
  'created_by',
  'created_at',
  'updated_at',
] as const

/** Everything except the key and created_at (the stale-write trigger keeps the original created_at anyway). */
const UPDATED_COLUMNS = FOOD_ITEM_COLUMNS.filter((column) => column !== 'id' && column !== 'created_at')

const HEADER = [
  '-- 003_seed_foods.sql — system food catalog (food_items rows with created_by = null).',
  '-- GENERATED FILE, do not edit by hand: generated by scripts/generate-seed-sql.ts (`npm run seed:sql`)',
  '-- from src/data/system-foods.json. A unit test fails when this file and the catalog drift apart.',
  '--',
  '-- Data source: U.S. Department of Agriculture, Agricultural Research Service. FoodData Central',
  '-- (https://fdc.nal.usda.gov). Each row cites its dataset and FDC id in the attribution column.',
  '-- License: public domain under CC0 1.0 Universal; FoodData Central asks to be cited as the source.',
  '--',
  "-- Idempotent: ids are deterministic (uuid v5 of 'system:' || slug, src/lib/id.ts systemFoodId), and",
  '-- re-running upserts every row in place. Rows are ordered by slug.',
]

interface SeedEntry {
  readonly slug: string
  readonly food: FoodRow
}

/** Validates the foods and orders them by slug (unique, so the order is total and locale-independent). */
function seedEntries(foods: readonly FoodRow[]): SeedEntry[] {
  if (foods.length === 0) throw new Error('generateSeedSql needs at least one food')
  const ids = new Set<string>()
  const entries = new Map<string, SeedEntry>()
  for (const food of foods) {
    if (food.source !== 'system' || food.createdBy !== null) {
      throw new Error(`"${food.name}" is not a system food (source "${food.source}", createdBy ${food.createdBy})`)
    }
    if (food.externalId === null) throw new Error(`System food "${food.name}" has no slug (externalId)`)
    if (ids.has(food.id)) throw new Error(`Duplicate food id ${food.id}`)
    if (entries.has(food.externalId)) throw new Error(`Duplicate food slug ${food.externalId}`)
    ids.add(food.id)
    entries.set(food.externalId, { slug: food.externalId, food })
  }
  return [...entries.values()].sort((a, b) => (a.slug < b.slug ? -1 : 1))
}

function valuesRow(food: FoodRow): string {
  const nutrients = Object.fromEntries(NUTRIENT_KEYS.map((key) => [key, food.per100g[key]]))
  const servings = food.servings.map((serving) => ({ label: serving.label, grams: serving.grams }))
  const lines = [
    [
      sqlUuid(food.id),
      sqlString(food.source),
      sqlNullableString(food.externalId),
      sqlString(food.name),
      sqlNullableString(food.brand),
      sqlNullableString(food.barcode),
      sqlNullableString(food.category),
    ],
    [sqlJsonb(nutrients)],
    [sqlJsonb(servings)],
    [
      sqlTextArray(food.allergens),
      sqlBoolean(food.dietFlags.vegetarian),
      sqlBoolean(food.dietFlags.vegan),
      sqlTextArray(food.tags),
      sqlTextArray(food.mealTypes),
      sqlInteger(food.prepMinutes),
      sqlBoolean(food.requiresCooking),
      sqlInteger(food.costTier),
    ],
    [
      sqlNullableString(food.attribution),
      'null', // created_by: system foods never have an owner (enforced by seedEntries)
      sqlTimestamptz(food.createdAt),
      sqlTimestamptz(food.updatedAt),
    ],
  ]
  return `  (${lines.map((parts) => parts.join(', ')).join(',\n   ')})`
}

/**
 * Renders an idempotent upsert of system foods into public.food_items.
 * Deterministic: output depends only on the foods (sorted by slug), never on time or input order.
 */
export function generateSeedSql(foods: readonly FoodRow[]): string {
  const entries = seedEntries(foods)
  return [
    ...HEADER,
    `-- ${entries.length} foods.`,
    '',
    `insert into public.food_items (${FOOD_ITEM_COLUMNS.join(', ')})`,
    'values',
    entries.map((entry) => valuesRow(entry.food)).join(',\n'),
    'on conflict (id) do update set',
    UPDATED_COLUMNS.map((column) => `  ${column} = excluded.${column}`).join(',\n'),
    // Never take over a user-owned row, even in the (practically impossible) case of an id collision.
    'where public.food_items.created_by is null;',
    '',
  ].join('\n')
}
