import { describe, expect, it } from 'vitest'
import initialSchemaSql from '../../supabase/migrations/001_initial_schema.sql?raw'
import committedSeedSql from '../../supabase/migrations/003_seed_foods.sql?raw'
import { SYSTEM_FOOD_ROWS, type SystemFoodRow } from '@/data/catalog'
import type { FoodRow } from '@/data/foodRow'
import { FOOD_ITEM_COLUMNS, generateSeedSql } from '@/data/seedSql'
import { SYSTEM_FOODS } from '@/data/systemFoods'
import { NUTRIENT_KEYS } from '@/types'

function sampleRow(overrides: Partial<FoodRow> = {}): FoodRow {
  const base: SystemFoodRow | undefined = SYSTEM_FOOD_ROWS[0]
  if (!base) throw new Error('catalog is empty')
  return { ...base, ...overrides }
}

/** Column names of public.food_items as declared in the canonical schema migration. */
function schemaColumns(): string[] {
  const start = initialSchemaSql.indexOf('create table public.food_items (')
  const end = initialSchemaSql.indexOf('\n);', start)
  const body = initialSchemaSql.slice(start, end).split('\n').slice(1)
  return body
    .map((line) => /^ {2}([a-z][a-z0-9_]*) [a-z]/.exec(line)?.[1])
    .filter((name): name is string => name !== undefined && name !== 'constraint')
}

/** Slugs (external_id, third value of each row) in the order the rows appear. */
function rowSlugs(sql: string): string[] {
  return [...sql.matchAll(/^ {2}\('[0-9a-f-]+'::uuid, 'system', '([a-z0-9_]+)'/gm)].map((match) => match[1] ?? '')
}

describe('generateSeedSql — committed migration', () => {
  it('is exactly what the generator produces from the catalog (no drift)', () => {
    expect(committedSeedSql).toBe(generateSeedSql(SYSTEM_FOOD_ROWS))
  })

  it('produces the same SQL from the typed FoodItem catalog', () => {
    expect(generateSeedSql(SYSTEM_FOODS)).toBe(committedSeedSql)
  })

  it('contains one row per system food, ordered by slug', () => {
    const slugs = rowSlugs(committedSeedSql)
    expect(slugs).toHaveLength(SYSTEM_FOODS.length)
    expect(slugs).toEqual(SYSTEM_FOODS.map((food) => food.externalId).sort())
    for (const food of SYSTEM_FOODS) expect(committedSeedSql).toContain(`('${food.id}'::uuid, 'system'`)
  })

  it('round-trips nutrient snapshots through the jsonb literal', () => {
    const banana = SYSTEM_FOODS.find((food) => food.externalId === 'banana')
    if (!banana) throw new Error('missing banana')
    const rowStart = committedSeedSql.indexOf(`('${banana.id}'::uuid`)
    const literal = /'(\{"calories".*?\})'::jsonb/.exec(committedSeedSql.slice(rowStart))?.[1]
    expect(literal).toBeDefined()
    const parsed: unknown = JSON.parse((literal ?? '').replaceAll("''", "'"))
    expect(parsed).toEqual(banana.per100g)
    expect(Object.keys(parsed as object)).toEqual([...NUTRIENT_KEYS])
  })

  it('documents its generator and the USDA public-domain source in the header', () => {
    const header = committedSeedSql.split('\ninsert into')[0] ?? ''
    expect(header).toContain('generated by scripts/generate-seed-sql.ts')
    expect(header).toContain('U.S. Department of Agriculture')
    expect(header).toContain('FoodData Central')
    expect(header).toContain('CC0')
  })
})

describe('generateSeedSql — statement shape', () => {
  it('inserts exactly the public.food_items columns of 001_initial_schema.sql, in order', () => {
    expect(schemaColumns()).toEqual([...FOOD_ITEM_COLUMNS])
    expect(committedSeedSql).toContain(`insert into public.food_items (${FOOD_ITEM_COLUMNS.join(', ')})`)
  })

  it('upserts by id, updating every column except id and created_at, and never takes over user rows', () => {
    const sql = generateSeedSql([sampleRow()])
    const updateClause = sql.slice(sql.indexOf('on conflict (id) do update set'))
    for (const column of FOOD_ITEM_COLUMNS.filter((name) => name !== 'id' && name !== 'created_at')) {
      expect(updateClause).toContain(`  ${column} = excluded.${column}`)
    }
    expect(updateClause).not.toContain('created_at = excluded.created_at')
    expect(sql.trimEnd().endsWith('where public.food_items.created_by is null;')).toBe(true)
  })

  it('is deterministic and independent of input order', () => {
    const reversed = [...SYSTEM_FOOD_ROWS].reverse()
    expect(generateSeedSql(reversed)).toBe(generateSeedSql(SYSTEM_FOOD_ROWS))
  })
})

describe('generateSeedSql — values', () => {
  it('escapes quotes in text and inside jsonb, keeping backslashes literal', () => {
    const row = sampleRow({
      name: `Grandma's "best" soup \\ v2`,
      servings: [{ label: "1 chef's bowl (250 g)", grams: 250 }],
      attribution: "O'Brien test",
    })
    const sql = generateSeedSql([row])
    expect(sql).toContain(`'Grandma''s "best" soup \\ v2'`)
    expect(sql).toContain(`'[{"label":"1 chef''s bowl (250 g)","grams":250}]'::jsonb`)
    expect(sql).toContain(`'O''Brien test'`)
  })

  it('renders unknown values as SQL null or JSON null, never as zero', () => {
    const base = sampleRow()
    const row = sampleRow({
      per100g: { ...base.per100g, fiber: null },
      allergens: null,
      dietFlags: { vegetarian: null, vegan: null },
      prepMinutes: null,
      requiresCooking: null,
      costTier: null,
      tags: [],
    })
    const sql = generateSeedSql([row])
    expect(sql).toContain('"fiber":null')
    expect(sql).toContain(`   null, null, null, '{}'::text[], `)
    expect(sql).toContain(', null, null, null,\n')
  })

  it('rejects text PostgreSQL cannot store', () => {
    expect(() => generateSeedSql([sampleRow({ name: 'bad\u0000byte' })])).toThrow(/NUL/)
  })
})

describe('generateSeedSql — guards', () => {
  it('requires at least one food', () => {
    expect(() => generateSeedSql([])).toThrow(/at least one/)
  })

  it('only seeds system foods without an owner', () => {
    expect(() => generateSeedSql([sampleRow({ source: 'custom' })])).toThrow(/not a system food/)
    const owner = '11111111-1111-4111-8111-111111111111'
    expect(() => generateSeedSql([sampleRow({ createdBy: owner })])).toThrow(/not a system food/)
    expect(() => generateSeedSql([sampleRow({ externalId: null })])).toThrow(/no slug/)
  })

  it('rejects duplicate ids and duplicate slugs', () => {
    const first = sampleRow()
    const otherId = '00000000-0000-5000-8000-000000000001'
    expect(() => generateSeedSql([first, sampleRow({ externalId: 'other_slug' })])).toThrow(/Duplicate food id/)
    expect(() => generateSeedSql([first, sampleRow({ id: otherId })])).toThrow(/Duplicate food slug/)
  })
})
